# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run build
    - run: npm run bundle
    - name: Upload theme bundle
      uses: actions/upload-artifact@v2
      with:
        name: theme-bundle
        path: /home/runner/work/techgnosis-theme/_s.zip
        retention-days: 5
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Download theme bundle
      uses: actions/download-artifact@v2
      with:
        name: theme-bundle
    - run: unzip _s.zip -d dist
    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -chav --exclude=".git" --exclude=".vscode" --include="dist/***"
        path: dist/
        remote_path: /home4/elysium001/webtechgnosis.com/wp-content/themes/test123
        remote_host: ${{ secrets.REMOTE_HOST }}
        remote_user: ${{ secrets.REMOTE_USER }}
        remote_key: ${{ secrets.HOST_KEY }}
